"""
Django settings for client_rest_api project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*c6dy3m$my1m-cf@19c=6d0m7w*gdf+vpn1p(x$n*l(t4pnb81'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CORS_ALLOWED_ORIGINS = [
    "http://192.168.15.63:5005", "http://localhost:5005","http://www.cosmicrms.com","https://www.cosmicrms.com","http://192.168.15.63:8500", "http://192.168.15.106:5005", "http://192.168.15.106:9009",
    "http://alphatrade.fortiddns.com:5000", "http://alphatrade.fortiddns.com",
    "http://alphatrade.fortiddns.com:5005", "http://localhost:8200", "http://192.168.15.106:8200", "http://alphatrade.fortiddns.com:8200", "http://alphatrade.fortiddns.com:5000","http://192.168.15.104:5000/","https://36af9a098a67.ngrok-free.app", "https://66730f27c2d6.ngrok-free.app","http://192.168.15.104:5000","http://192.168.15.104:5173", "https://98235865df4b.ngrok-free.app",
]
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'user',
    'activeId',
    'user_id',   
    'auth-token',  
    'Auth_token' 
]


CSRF_COOKIE_NAME = 'csrftoken'
CSRF_COOKIE_AGE = 86400
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False
CSRF_TRUSTED_ORIGINS = [
    "http://192.168.15.63:5005", "http://localhost:5005","http://www.cosmicrms.com","https://www.cosmicrms.com","http://192.168.15.106:5005",  
    "http://192.168.15.106:9009", "http://alphatrade.fortiddns.com:5000", "http://alphatrade.fortiddns.com",
    "http://alphatrade.fortiddns.com:5005", "http://localhost:8200", "http://192.168.15.106:8200", "http://alphatrade.fortiddns.com:8200", "http://alphatrade.fortiddns.com:5001","https://36af9a098a67.ngrok-free.app", "https://66730f27c2d6.ngrok-free.app","http://192.168.15.104:5000","http://192.168.15.104:5173", "https://98235865df4b.ngrok-free.app"
]
CSRF_COOKIE_HTTPONLY = False 


# Application definition

INSTALLED_APPS = [
    'apps.payment',
    'apps.core',
    'apps.users',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'apps.core.middleware.DynamicUserTokenMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'client_rest_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'client_rest_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    # Existing SQLite database
    'default': {
        'ENGINE': os.environ['DB_ENGINE'],
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASSWORD'],
        'HOST': os.environ['DB_HOST'],
        'PORT': os.environ.get('DB_PORT', '5432'),  # optional with default
    },
    'replica': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'crmdb',      # replace with actual MySQL DB name
        'USER': 'db_readonly',
        'PASSWORD': '67JQUZHmxbmU4tMn',
        'HOST': 'spectra-replica-db.cxq42qwo0p8j.eu-west-1.rds.amazonaws.com',
        'PORT': '3306'
        }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
